### ISSUE TITLE
error while sending get_reachable request

### ISSUE THREAD

**Issue by ErfanGerami** [AI-Cup-Kernel/Kernel-web-server-version#22]
I think that it was assumed that every node has an owner instead of its owner being None
 ERROR in app: Exception on /get_reachable [POST]
Traceback (most recent call last):
  File "C:\Users\Geramizade\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\Documents\Projects\IUT\Kernel-web-server-version\src\tools\check_token.py", line 37, in decorator
    return func(data['player_id'])
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\Documents\Projects\IUT\Kernel-web-server-version\src\tools\check_player.py", line 16, in decorator
    return func(player_id)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\Documents\Projects\IUT\Kernel-web-server-version\src\blueprints\get_reachable.py", line 34, in get_reachable_func
    output_dict = {"reachable":find_reachable(node_id,main_game)}
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\Documents\Projects\IUT\Kernel-web-server-version\src\tools\find_reachable.py", line 20, in find_reachable
    DFS(node_id, main_game, main_game.nodes[node_id].owner.id)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
127.0.0.1 - - [22/Aug/2023 23:03:40] "POST /get_reachable HTTP/1.1" 500 -
start turn: 32
[2023-08-22 23:03:42,038] ERROR in app: Exception on /get_reachable [POST]
Traceback (most recent call last):
  File "C:\Users\Geramizade\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\Documents\Projects\IUT\Kernel-web-server-version\src\tools\check_token.py", line 37, in decorator
    return func(data['player_id'])
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\Documents\Projects\IUT\Kernel-web-server-version\src\tools\check_player.py", line 16, in decorator
    return func(player_id)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\Documents\Projects\IUT\Kernel-web-server-version\src\blueprints\get_reachable.py", line 34, in get_reachable_func
    output_dict = {"reachable":find_reachable(node_id,main_game)}
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\Documents\Projects\IUT\Kernel-web-server-version\src\tools\find_reachable.py", line 20, in find_reachable
    DFS(node_id, main_game, main_game.nodes[node_id].owner.id)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
127.0.0.1 - - [22/Aug/2023 23:03:42] "POST /get_reachable HTTP/1.1" 500 -
start turn: 33
[2023-08-22 23:03:43,037] ERROR in app: Exception on /get_reachable [POST]
Traceback (most recent call last):
  File "C:\Users\Geramizade\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\Documents\Projects\IUT\Kernel-web-server-version\src\tools\check_token.py", line 37, in decorator
    return func(data['player_id'])
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\Documents\Projects\IUT\Kernel-web-server-version\src\tools\check_player.py", line 16, in decorator
    return func(player_id)
           ^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\Documents\Projects\IUT\Kernel-web-server-version\src\blueprints\get_reachable.py", line 34, in get_reachable_func
    output_dict = {"reachable":find_reachable(node_id,main_game)}
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Geramizade\Documents\Projects\IUT\Kernel-web-server-version\src\tools\find_reachable.py", line 20, in find_reachable
    DFS(node_id, main_game, main_game.nodes[node_id].owner.id)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by mamadmr** [comment]
fixed
